version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_emocional
    restart: always
    environment:
      POSTGRES_DB: emocional
      POSTGRES_USER: arthurfaria
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    container_name: grafana_emocional
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  pgdata:
